language:
  - java
jdk:
  - oraclejdk7
  - oraclejdk8
env:
  global:
  - secure: |-
      x85VA9iP+/ZkBaWiupbGeJBDM4MBTp98yBVnWIe+vbWMj07zmvrIfM6rsdgT
      hZ1uBgEzGfpZ/vnU8CQN6KYXmyG2Vy4j2RlOhHf7aChNh38VzCq+97gXmLCR
      2vwy+FPJQLEWklEbUPkbiaoGwn0TxIg2Q2LpEeSBuJy82aAXaFc=
  - secure: |-
      0N0Egg/il0d8zktIgVLrbkVnNaULIEhA7k/VufIiA1VqRtU2s63tvbEqkh8t
      7SvCgLvni0ewVVs8P2F9dGeG7HZ0WRJ3tcdZCcJG9IBk6xNcWAQveZ2goBKJ
      0Y0YksLljdKHv8mn02KX2tZxLVYjgzq09Dvn0+bGOzQU+TLbkPY=
before_script:
  - sbt update
  - nvm install 0.12
  - nvm use 0.12
  - npm install -g npm@latest
  - node --version
  - npm --version
  - npm config set spin false
  - pushd javascript ; npm install ; popd
script:
  - pushd javascript ; (npm test && node_modules/.bin/gulp deploy-prod) ; popd
  - sbt test
after_success:
  - sbt universal:package-zip-tarball
deploy:
  provider: s3
  access_key_id: AKIAIGYGO43W76PZMMVA
  secret_access_key:
    secure: YIOoh0TlzEVkjgayLKSi/a3k+CTuv4rZhouq2rDtdgURgt1D4E/GboTgjVQ76UJRU2R3deLlt9VJo4f2kwyed9p1OFTMPaeX8LU1CPx4chZDzl4a1sZG/uxfrIy/xXgPM3oGjK9X0+fV3oDPhEAqFl2WveMw/8SU06yf8MxrHrM=
  bucket: graylog2-builds
  region: eu-west-1
  skip_cleanup: true
  local-dir: target/universal
  on:
    repo: Graylog2/graylog2-web-interface
    jdk: oraclejdk7
    branch:
      - master
      - 1.0
addons:
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: |-
        g6Gpj2n1Bl6hIwWlywEkw8wRjpN2XuFsxFr9KQu/p7mRLYPdF3V5qQPVLBRd
        KvkjCIM7gZy2DTRNUooQPXdJB3npbnlbQn4jNWqA7/fp434Sw5sdfSUMawGr
        XvemLvn0KxQxCO9GfN3wfmYxEWJwXO36Q29BnRWWgMQOXpFFD8A=
