; settingsfile for shell.rake
; 
; [anySectionname]
; disabled=yes      ; ignore this section
; title=Caption     ; any caption for this secton
; query=all.count() ; Graylog2 Analytics Shell Query
; limit=20          ; sets the maximum of replyd lines
; sendmail=yes      ; sends the result as mail, no will show result on console
; mailto=e@mail.com f@mail.com ; sends mail to these addresses, multiply address split by space
; template=plain    ; use the template in file "shell_[type]_plain.erp"

[404_t20]
disabled=no
title=Top 20 - HTTP 404 - File Not Found
query=stream(http404).distribution({_request}, created_at > <%= (Time.now-1*24*60*60).to_i %>)
limit=20
sendmail=no
mailto=user1@example.com user2@example.com
template=plain

