# osx
development:
  enable_graphs: true
  rrdtool_binary_path: /usr/local/bin/rrdtool
  rrd_storage_path: /tmp/rrd/

# ubuntu  
production:
  enable_graphs: true
  rrdtool_binary_path: /usr/bin/rrdtool
  rrd_storage_path: /var/lib/rrd
